### ISSUE TITLE
End-to-end flow for createFile operation 

### ISSUE THREAD

**Issue by Pralhad-Deshpande** [anquan-codebase/namic-3dm-project-management#1]
A createFile endpoint should be offered by the proxy. This endpoint should help a user upload a new file into S3. 

The parameters for this end-point should be ReadPermission, WritePermission, Owner, file. 

Example: POST http://proxy.com/createfile/file?uploadType=media/readpermission?*/writepermission?alice/owner?alice

User should use this endpoint to upload a file onto S3 storage. 

The proxy should compute the hash of this file. 

The proxy should invoke the S3 api to upload this new file. 

The return status should be captured (200) at the proxy

At this time the proxy will have all information necessary to write to the blockchain

Proxy makes an async call to a logging smart contract on the blockchain to log the below JSON structure. 

{
    “Operation” : “CreateFile”, 
    “Filename”: ”/home/Alice/filename”, //absolute path 
    “RequestFrom”: “Alice”, 
    “RequestTime”: “001”, //timestamp recorded at proxy
    “SHA256hash” : “0x...”, 
    “ReturnStatus” : “success”, //200 --->// only considering http status
    “ReadPermission” : “*”, 
    “WritePermission” : “Alice”, 
    “Owner” : “Alice” 
}

**Comment by Pralhad-Deshpande** [comment]
@zoeylee02, this is as per our phone conversation today. If anything is unclear please comment here. Thanks! -- PD

**Comment by Pralhad-Deshpande** [comment]
@zoeylee02, instead of writing to a smart contract on the blockchain, we can append the json to a file for now. Please target finishing this issue by today except for the blockchain part. 

Thanks, 

PD

**Comment by Pralhad-Deshpande** [comment]
OK, is only CreateFile done or other operations are also done? I see code in the above link for other operations as well.

**Comment by zoeylee02** [comment]
Update data/Read File/Delete/Change Owner/Update Premissions  also done.
