### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by Pralhad-Deshpande** [anquan-codebase/namic-3dm-project-management#10]
Create a docker container including:

1. proxy
2. mongodb
3. journal 
4. cron job

**Comment by zoeylee02** [comment]
pushed docker images to docker hub.

[Repositories]
1)   zoeylee02 / ledger-database
  -  https://hub.docker.com/r/zoeylee02/ledger-database

2)  zoeylee02 / mongodb 
    - https://hub.docker.com/r/zoeylee02/mongodb
