### ISSUE TITLE
stored procedure in mongodb

### ISSUE THREAD

**Issue by Pralhad-Deshpande** [anquan-codebase/namic-3dm-project-management#3]
In MongoDB, create two tables. 

Table 1: current.cars, schema: {ID, Manufacturer, Model, Year, VIN, Owner}

Table 2: history.cars, schema: {ID, Version, Timestamp, Manufacturer, Model, Year, VIN, Owner}

When a new record is created in current.cars, a new record should be created in history.cars with version 1. When a record is updated in current.cars, a new record should be created in history.cars with the next version number. Write a stored procedure to do this. 

I will email you slides showing the desired result. Please go through the slides and let me know by commenting on this issue if your understanding regarding this work item is clear.

**Comment by zoeylee02** [comment]
Done:
1. Already Created function for storing data to history table.
`db.system.js.save(
   {
     _id: "storeHistory",
     value : function(res, operationType) { 
        db.history.save({
           "_id": getNextSequenceValue('historyid'),
           "Version": 1,
           "Start": getToday(),
           "OperationType": operationType,
           "Manufacturer": res.Manufacturer,
           "Model": res.Model,
           "Year": res.Year,
           "VIN": res.VIN,
           "Owner": res.Owner
         });
     }
   }
)`

`rs0:PRIMARY> db.current.save(item, storeHistory(item, "insert"));
 rs0:PRIMARY>db.current.update({"_id":1}, item, storeHistory(item, "update"))`
`
Next:
1. add watch feature for storing history automatically when listening insert, update and delete.
`db.current.watch()`

**Comment by zoeylee02** [comment]
**[Done]**

1. add init.js for mongo shell
- create functions for stored procedure
- create counters table for auto increment

2. add watch events for listening data changes
- store data to history when trigger insert/update/delete event

**Comment by Pralhad-Deshpande** [comment]
We had to iterate over this a few times to get it just right. I am going to close this issue now. Well done @zoeylee02 !
