### ISSUE TITLE
Improve randomness of hash value

### ISSUE THREAD

**Issue by Pralhad-Deshpande** [anquan-codebase/namic-3dm-project-management#8]
At the moment, each entry in the hash chain is recorded as follows. 

{
    "tx": "2019-01-09 01:54:18.536 QUERY     [current] : {}. 1 returned.\n",
    "hash": "fb6ee14e97882e4e5a01d77b09e0460acb4a8bf4233356ea1bc6f44e71f15d01"
}

We should add some randomness to the entry so that the hash value becomes less predictable. This can be done by adding a random salt entry to the log. So the entry should look like follows: 

{
    "tx": "2019-01-09 01:54:18.536 QUERY     [current] : {}. 1 returned.\n",
    "salt": "E1F53135E559C253",
    "hash": "fb6ee14e97882e4e5a01d77b09e0460acb4a8bf4233356ea1bc6f44e71f15d01"
}

hash should be computed as: 

hash = SHA256(prev_hash + tx + salt).

**Comment by zoeylee02** [comment]
Output
```
(env) zoey@zoey-ThinkPad-T480:~/Desktop/codebase/auditable-database/mongotail$ python mongotail.py cars -f
{
    "tx": "2019-01-14 08:38:27.501 INSERT    [current] : 1 inserted.\n",
    "salt": "4CF18AB621A749C2",
    "hash": "23ccb5684fcecb0f9d0bbaca39a0215c05834cb697a0d630e47a8d1e6497c905"
}
{
    "tx": "2019-01-14 08:38:27.507 QUERY     [history] : {\"ID\": ObjectId(\"5c3c4a8388462633fb99812e\")}, sort: {\"Version\": -1.0}. 0 returned.\n",
    "salt": "B0379E059ABD47EB",
    "hash": "b7a0eec527b51fdbb96ddf8636994607bf0c8fb67564589f7a6b0962dff9968c"
}
{
    "tx": "2019-01-14 08:38:27.509 INSERT    [current_history] : 1 inserted.\n",
    "salt": "0F7C24B4135640C4",
    "hash": "77ff262ec50f3ca5d36f2fcec361485c593f0ed83a6e20ee445edfc62a13485b"
}
```

**Comment by Pralhad-Deshpande** [comment]
UUID is used to generate salt.
